/**
 * docs.mjs — Render assistant/human docs from the live catalog (see catalog.mjs).
 *
 *   renderLlmsTxt(cat)     → llms.txt (llmstxt.org style, for LLMs)
 *   renderDeepLinksMd(cat) → docs/DEEPLINKS.md (for people)
 *
 * Used by tools/gen-docs.mjs (writes the files) and by mcp/server.mjs (serves them as resources,
 * rendered on the fly so they can never be stale).
 */
import { capabilityNote, describeRange } from './catalog.mjs';

export const REPO_URL = 'https://github.com/HandHeldLegend/handheldlegend.github.io';
export const MCP_SOURCE_URL = `${REPO_URL}/tree/master/hoja3/mcp`;
const GENERATED = 'Generated by tools/gen-docs.mjs from src/sections/registry.js and src/settings/schema.js — do not edit by hand.';

/** Escape a value for a Markdown table cell. */
const cell = (s) => String(s ?? '').replace(/\|/g, '\\|').replace(/\r?\n/g, ' ').trim();
const code = (s) => `\`${String(s).replace(/`/g, "'")}\``;

/** Settings grouped by page, in page order (settings for unknown sections go last). */
function settingsByPage(cat) {
  const groups = cat.pages.map((p) => ({ page: p, settings: cat.settingsFor(p.id) })).filter((g) => g.settings.length);
  const known = new Set(cat.pages.map((p) => p.id));
  const orphans = cat.settings.filter((s) => !known.has(s.section));
  if (orphans.length) groups.push({ page: { id: 'other', title: 'Other' }, settings: orphans });
  return groups;
}

/** A couple of real example links, picked from whatever settings exist. */
function examples(cat) {
  const out = [];
  // Prefer friendly, low-risk examples when they exist; fall back to whatever the catalog has.
  const pick = (keys, pred) => keys.map((k) => cat.getSetting(k)).find((s) => s && pred(s)) || cat.settings.find(pred);
  const num = pick(['haptics.intensity', 'rgb.brightness', 'joysticks.leftDeadzone'], (s) => s.type === 'number' && s.min != null && s.max != null);
  const bool = cat.settings.find((s) => s.type === 'boolean' && s.section === num?.section) || cat.settings.find((s) => s.type === 'boolean');
  const en = pick(['rgb.mode', 'snapback.leftType'], (s) => s.type === 'enum');
  if (num) {
    const mid = Math.round(((num.min + num.max) / 2) / (num.step || 1)) * (num.step || 1);
    const values = { [num.key]: mid };
    if (bool) values[bool.key] = true;
    const plan = cat.planSettingsLink(values, { then: num.section });
    if (plan.url) out.push({ title: `Set ${num.key} to ${mid}${num.unit === '%' ? '%' : ''}${bool ? ` and ${bool.key} on` : ''}`, url: plan.url });
  }
  if (en) {
    const opt = en.options[Math.min(1, en.options.length - 1)];
    const plan = cat.planSettingsLink({ [en.key]: opt.value });
    if (plan.url) out.push({ title: `Set ${en.key} to ${opt.label}`, url: plan.url });
  }
  return out;
}

function pageExamples(cat) {
  const out = [];
  for (const p of cat.pages) {
    const choiceParams = p.params.filter((x) => x.choices);
    if (!choiceParams.length) continue;
    const params = Object.fromEntries(choiceParams.map((x) => [x.name, x.choices[0]]));
    const r = cat.pageUrl(p.id, params);
    if (r.ok) out.push({ title: `${p.title} (${Object.entries(params).map(([k, v]) => `${k}=${v}`).join(', ')})`, url: r.url });
    if (out.length >= 3) break;
  }
  return out;
}

function pagesTable(cat, { urls = true } = {}) {
  const rows = cat.pages.map((p) => {
    const params = p.params.length ? p.params.map((x) => `${code(x.name)}: ${x.description}`).join('<br>') : '—';
    const needs = p.needsController ? (p.requires ? `Controller + ${p.requires}` : 'Controller') : '—';
    return `| ${code(urls ? p.url.slice(cat.base.length) : p.id)} | ${cell(p.title)} | ${cell(p.summary)} | ${cell(needs)} | ${cell(params)} |`;
  });
  return ['| Route | Page | What it’s for | Needs | Deep-link params |', '|---|---|---|---|---|', ...rows].join('\n');
}

function settingsTables(cat) {
  return settingsByPage(cat).map(({ page, settings }) => [
    `### ${page.title} (${code(page.id)})`,
    '',
    '| Key | Label | Values | Needs | Description |',
    '|---|---|---|---|---|',
    ...settings.map((s) => `| ${code(s.key)} | ${cell(s.label)} | ${cell(describeRange(s))} | ${cell(s.requires || '—')} | ${cell(s.description || '')} |`),
  ].join('\n')).join('\n\n');
}

function capabilityList(cat) {
  const used = new Set([...cat.pages.map((p) => p.requires), ...cat.settings.map((s) => s.requires)].filter(Boolean));
  return [...used].sort().map((f) => `- ${code(f)} — ${capabilityNote(f)}`).join('\n');
}

const SAFETY = [
  'Links never change anything silently. Opening an `#/apply` link shows a “before → after” list and the user must press **Apply** or **Apply & save**; **Cancel** discards it.',
  'The controller must be connected over USB in a Chromium-based browser (Chrome, Edge, Opera, Brave… on desktop or Android). iPhone/iPad browsers cannot connect to controllers.',
  'Changes apply to the controller immediately but are only kept after a power cycle once saved (**Save** in the top bar, or **Apply & save**).',
  'Settings the connected controller doesn’t have hardware for are shown as “Not supported” and skipped.',
  'Firmware installs, calibration, button remapping and pairing are deliberately *not* settable by link — send the user to the page instead (e.g. `#/joysticks?stick=left`).',
  'Assistants should explain what a link will change before sharing it and never claim a change was made — only the user can confirm it.',
];

/** llms.txt — the whole app described for LLMs. */
export function renderLlmsTxt(cat) {
  const ex = examples(cat);
  return `# HHL Gamepad Config

> HHL Gamepad Config (internal name hoja3) is Hand Held Legend’s free, offline-first web app (PWA) for configuring game controllers that run HOJA firmware — e.g. GC Ultimate, ProGCC and Super Gamepad+. It connects over USB with WebUSB, updates firmware, and is fully deep-linkable so assistants can send customers straight to the right page or a pre-filled set of settings. App URL: ${cat.base}

<!-- ${GENERATED} -->

Key facts:

- Works in Chromium browsers (Chrome, Edge, Opera, Brave…) on desktop and Android, served over https. Not on iPhone/iPad (no WebUSB); the demo and Arena still work there.
- Connect with a USB **data** cable. Only **Switch** and **Steam (SInput)** output modes talk to the app; if a controller starts in another mode, unplug it and hold **A** (South) while plugging it back in.
- Every change applies live; **Save** writes it to the controller’s flash so it survives unplugging.
- Try it without hardware: ${cat.base}?demo (a simulated controller).
- Routing is hash-based: ${code(`${cat.base}#/<page>?<param>=<value>`)}.

## Deep links

- Open a page: ${code(`${cat.base}#/<page>[?param=value&…]`)} — e.g. ${pageExamples(cat).map((e) => code(e.url)).join(', ') || code(`${cat.base}#/firmware`)}
- Propose settings: ${code(`${cat.base}#/apply?<setting.key>=<value>&…&then=<page>`)}. Keys come from the catalog below; values are validated (numbers are clamped to the step, enums accept the value, label or an alias, booleans accept on/off/true/false/1/0, colors are #rrggbb). ${code('then')} picks the page shown afterwards. The user sees a confirmation dialog before anything is written.
${ex.map((e) => `- Example — ${e.title}: ${e.url}`).join('\n')}
- Pages that need a controller show a “Connect” prompt until one is connected, then open the requested view.

## Pages

${pagesTable(cat)}

Capability flags used in “Needs” columns (detected from the connected controller):

${capabilityList(cat)}

## Settings catalog

${cat.settings.length} settings can be read and proposed by key. Anything not listed (calibration, button remapping, angle maps, pairing, firmware) is done interactively on its page.

${settingsTables(cat)}

## Safety

${SAFETY.map((s) => `- ${s}`).join('\n')}

## Docs

- [Deep links (human guide)](${cat.base}docs/DEEPLINKS.md): every page, parameter and setting with examples.
- [Troubleshooting knowledge base](${cat.base}docs/KNOWLEDGE.md): connecting, browsers, calibration, drift, snapback, firmware updates, recovery, wireless, battery, saving, iOS.
- [MCP server](${MCP_SOURCE_URL}): a zero-dependency Model Context Protocol server (\`node hoja3/mcp/server.mjs\`) exposing list_pages, list_settings, describe_setting, build_page_link, build_settings_link, troubleshoot and list_firmware_builds.

## Optional

- In-page bridge: when the app is open, \`window.hhl\` offers status(), listPages(), listSettings(), getSetting(key), navigate(page, params) and proposeSettings({key: value}) (always asks the user to confirm). The same tools are registered with the browser’s WebMCP API (\`navigator.modelContext\`) when available.
- [Source code](${REPO_URL}/tree/master/hoja3)
`;
}

/** docs/DEEPLINKS.md — the same information, written for people. */
export function renderDeepLinksMd(cat) {
  const ex = examples(cat);
  const pex = pageExamples(cat);
  return `# Deep links

<!-- ${GENERATED} -->

Every page of HHL Gamepad Config has its own link, and links can carry settings. Use them in support
replies, manuals, videos and QR codes — or let an AI assistant build them (see [the MCP server](../mcp/README.md)).

Base URL: ${cat.base}

## Opening a page

\`\`\`
${cat.base}#/<page>?<param>=<value>&…
\`\`\`

${pex.map((e) => `- ${e.title}: <${e.url}>`).join('\n') || `- Firmware: <${cat.base}#/firmware>`}

Add \`?demo\` before the \`#\` to try any page with a simulated controller, e.g. <${cat.base}?demo#/joysticks>.

${pagesTable(cat)}

If the page needs a controller, it asks the customer to connect first and then opens. If the controller doesn’t
have the hardware (for example a page that needs \`imu\` on a controller without a gyro), the page explains that.

## Suggesting settings

\`\`\`
${cat.base}#/apply?<setting.key>=<value>&<setting.key>=<value>&then=<page>
\`\`\`

${ex.map((e) => `- ${e.title}:\n  <${e.url}>`).join('\n')}

What the customer sees:

1. The app opens the \`then\` page (Home if omitted) and shows **Apply suggested settings?** with a
   *current → new* line per setting.
2. If no controller is connected yet, the dialog waits and offers **Connect**.
3. **Apply** pushes the changes live; **Apply & save** also writes them to flash. **Cancel** changes nothing.
4. Settings the controller can’t use are marked *Not supported* and skipped; invalid entries are listed and ignored.

Value formats: numbers (a trailing \`%\` is fine; values snap to the setting’s step and must be in range), on/off
(\`on\`, \`off\`, \`true\`, \`false\`, \`1\`, \`0\`, \`yes\`, \`no\`), choices (the value, its label or an alias — case-insensitive),
colors (\`#rrggbb\` or \`#rgb\`; encode \`#\` as \`%23\` in hand-written links), text (URL-encoded).

## Settings reference

${settingsTables(cat)}

### Capability flags

${capabilityList(cat)}

## Not available by link

Stick and trigger calibration, button remapping, angle maps, Bluetooth pairing and firmware installs need the
customer at the controller — link to the page instead (for example \`#/joysticks?stick=left&tab=calibrate\`).

## For assistants and integrators

- [\`mcp/server.mjs\`](../mcp/README.md) — Model Context Protocol server that lists pages and settings and builds validated links.
- [\`llms.txt\`](../llms.txt) — this catalog in a compact form for LLMs.
- \`window.hhl\` — in-page bridge (status, navigate, proposeSettings with confirmation), also registered with WebMCP when the browser supports it.
`;
}
