/**
 * sw.js — Service worker: full offline support with an explicit, user-visible update flow.
 *
 * - install:  precache every file listed in precache-manifest.js (generated by tools/precache.mjs),
 *             posting { type: 'precache-progress', done, total } to open pages for the progress UI.
 * - activate: delete caches from older versions.
 * - fetch:    same-origin GETs are served cache-first (navigations fall back to index.html);
 *             cross-origin requests (GitHub firmware downloads, update manifests) go straight to the
 *             network and are never cached, so firmware checks are always fresh.
 * - message:  'skip-waiting' lets the page apply a waiting update when the user taps Restart.
 */
importScripts('precache-manifest.js');

const { version, files } = self.__PRECACHE;
const CACHE = `hhl-config-${version}`;
const PREFIX = 'hhl-config-';
const CONCURRENCY = 6;

async function broadcast(msg) {
  const clients = await self.clients.matchAll({ includeUncontrolled: true, type: 'window' });
  for (const c of clients) c.postMessage(msg);
}

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    const queue = [...files];
    let done = 0;
    const total = queue.length;
    await broadcast({ type: 'precache-progress', done, total, version });
    const worker = async () => {
      while (queue.length) {
        const url = queue.shift();
        const res = await fetch(new Request(url, { cache: 'reload' }));
        if (!res.ok) throw new Error(`precache ${url}: ${res.status}`);
        await cache.put(url, res);
        done += 1;
        if (done % 4 === 0 || done === total) broadcast({ type: 'precache-progress', done, total, version });
      }
    };
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys.filter((k) => k.startsWith(PREFIX) && k !== CACHE).map((k) => caches.delete(k)));
    await self.clients.claim();
  })());
});

self.addEventListener('message', (event) => {
  if (event.data?.type === 'skip-waiting') self.skipWaiting();
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin) return; // network only, never cached
  const scope = new URL(self.registration.scope);
  if (!url.pathname.startsWith(scope.pathname)) return;

  event.respondWith((async () => {
    const cache = await caches.open(CACHE);
    if (req.mode === 'navigate') {
      return (await cache.match('./')) || (await cache.match('index.html')) || fetch(req);
    }
    const hit = await cache.match(req, { ignoreSearch: true });
    if (hit) return hit;
    try {
      return await fetch(req);
    } catch {
      return new Response('Offline and not cached', { status: 504, headers: { 'Content-Type': 'text/plain' } });
    }
  })());
});
