#!/usr/bin/env node
/**
 * precache.mjs — Generate precache-manifest.js: every file the app needs offline + a content hash.
 *
 *   node tools/precache.mjs
 *
 * Run this before deploying (the GitHub Action / pre-commit can run it too). The service worker
 * (sw.js) imports the manifest; because the version is a hash of all file contents, any change to
 * any shipped file produces a new service worker and triggers the in-app "Update ready" flow.
 *
 * Shipped: index.html, manifest, llms.txt, css/, src/, assets/ (minus iOS splash images), vendor/, firmware/.
 * Not shipped: tools/, mcp/, docs/, markdown, package.json, dotfiles.
 */
import { readdir, readFile, writeFile, stat } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const OUT = path.join(ROOT, 'precache-manifest.js');

const INCLUDE_ROOT_FILES = ['index.html', 'manifest.webmanifest', 'llms.txt'];
const INCLUDE_DIRS = ['css', 'src', 'assets', 'vendor', 'firmware'];
const EXCLUDE = [
  /^assets\/icons\/splash\//,   // iOS fetches launch images itself at install time
  /^assets\/icons\/preview\.html$/,
  /(^|\/)\./,                    // dotfiles
  /\.md$/i,
  /\.map$/i,
  /LICENSE/i,
];

async function walk(dir) {
  const out = [];
  let entries = [];
  try { entries = await readdir(path.join(ROOT, dir), { withFileTypes: true }); } catch { return out; }
  for (const e of entries) {
    const rel = path.posix.join(dir, e.name);
    if (e.isDirectory()) out.push(...await walk(rel));
    else out.push(rel);
  }
  return out;
}

async function main() {
  const files = [];
  for (const f of INCLUDE_ROOT_FILES) if (await stat(path.join(ROOT, f)).catch(() => null)) files.push(f);
  for (const d of INCLUDE_DIRS) files.push(...await walk(d));
  const shipped = files.filter((f) => !EXCLUDE.some((re) => re.test(f))).sort();

  const hash = createHash('sha256');
  let bytes = 0;
  for (const f of shipped) {
    const buf = await readFile(path.join(ROOT, f));
    bytes += buf.length;
    hash.update(f).update(buf);
  }
  const pkg = JSON.parse(await readFile(path.join(ROOT, 'package.json'), 'utf8'));
  const version = `${pkg.version}+${hash.digest('hex').slice(0, 8)}`;

  const text = `// GENERATED by tools/precache.mjs — do not edit. Run: node tools/precache.mjs
// Works as a classic script (service worker importScripts) and as a module (page import).
self.__PRECACHE = ${JSON.stringify({ version, bytes, files: ['./', ...shipped] }, null, 1)};
`;
  await writeFile(OUT, text);
  console.log(`precache-manifest.js: ${shipped.length} files, ${(bytes / 1024 / 1024).toFixed(2)} MB, version ${version}`);
}

main().catch((err) => { console.error(err); process.exit(1); });
